### ISSUE TITLE
View 2.0

### ISSUE THREAD

**Issue by dan-koller** [dan-koller/view-crm#21]
# Overview

View is a pretty solid platform for managing projects. Therefore, it should be treated as such an not just a crm tool.

## Tasks

- [ ] Improve UI using `Angular`
- [ ] Update tests and make them more robust using `moq`
- [ ] Update start scripts (like those in `pow-captcha`)
